name: Lint / Test / IT

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:

jobs:
  azure-lint:
    name: azure-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          working-directory: azure

  azure-test:
    name: azure-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Run Unit tests
        run: make test
        working-directory: ./azure
